### ISSUE TITLE
another travis failure

### ISSUE THREAD

**Issue by bojum** [jtr13/cc19#153] opened 2019-11-02 03:34 UTC
Travis is getting the following error on #112 and #95.

![Screen Shot 2019-11-01 at 11 29 37 PM](https://user-images.githubusercontent.com/54489225/68065440-b8df1b00-fcff-11e9-97b5-ff972be484ff.png)

**Comment by bojum** [comment] 2019-11-02 03:38
This is the same error as mentioned in issue #151

**Comment by jtr13** [comment] 2019-11-02 12:48
Correct. The problem is a function conflict with "select". I'll fix it.

**Comment by jtr13** [comment] 2019-11-02 13:53
FYI, this is going to keep happening: I'm working on fixing this globally so it won't be necessary to namespace (`dplyr::select()`)  all the conflicted functions.

**Comment by jtr13** [comment] 2019-11-02 15:40
I'm hoping #155 will fix these problems, but I'm also wondering if we're placing too much weight on the results of the Travis PR build. If, for example, the PR branch has an old version of `.travis.yml`, the build is going to fail, despite the fact that there wouldn't be any issue with merging the pull request. I'm going to research this more, but my hunch is that we're wasting time making sure the Travis build passes before merging the pull request. The exception would be if the problem is in the `.Rmd` itself. In that case, the solution might be to find a way to test the `.Rmd` with the current setup in master not with the old files in the PR branch.

**Comment by jtr13** [comment] 2019-11-03 00:00
So that's not correct.  Travis _is_ testing what would happen if the pull request is merged. However, it tests when the pull request is made, so if there's a problem with master at that time, it will fail. That can be fixed by syncing the PR branch (as it seems you are doing) or I believe by restarting the Travis build. In any case, it looks like we're in better shape with Travis. I'll close this issue but let's continue to open issues if there's a problem with Travis.

**Closed as completed by jtr13** 2019-11-03 00:00 UTC
